name: dist_inf
channels:
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.6
  - torchvision==0.11.2
  - pylint
  - flake8
  - torchaudio
  - cudatoolkit=11.1
  - pytorch==1.10.1

